image: golang:1.25-alpine

pages:
  stage: deploy
  script:
    - apk add --no-cache git bash
    - go install github.com/gohugoio/hugo@latest
    - export PATH=$PATH:$(go env GOPATH)/bin
    - hugo mod get -u ./...
    - hugo mod tidy
    - hugo --minify
  artifacts:
    paths:
      - public
  only:
    - main
